language: python

dist: trusty

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

# linux deps
addons:
  apt:
    packages:
      - mlocate
      - coreutils
      - python-virtualenv

# osx deps
before_install:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && { brew list python &>/dev/null || brew install python; }
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install pyenv-virtualenv

install:
  - python setup.py install

script:
  - make test

matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py35
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - os: osx
